# Generated by Django 3.1 on 2020-08-26 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trvdjango', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trip',
            new_name='Trips',
        ),
    ]
